import { useState, useMemo } from "react";
import { useFRLiveSearch } from "./useFRLiveSearch";
import { FR_SEARCH_URL } from "./frQuery";
import DATA from "./data/filings.json";

const ROUTINE_USE = `To the U.S. Department of the Treasury when disclosure of the information is relevant to review payment and award eligibility through the Do Not Pay Working System for the purposes of identifying, preventing, or recouping improper payments to an applicant for, or recipient of, Federal funds, including funds disbursed by a state (meaning a state of the United States, the District of Columbia, a territory or possession of the United States, or a federally recognized Indian tribe) in a state-administered, federally funded program.`;

// Everything below is generated by `npm run update-data` (scripts/fetch-filings.mjs)
// from the live Federal Register API, merged with src/data/overrides.json.
// Do not hand-edit src/data/filings.json — edit overrides.json instead.
const AGENCIES = DATA.agencies;
const KNOWN_FR_DOCS = AGENCIES.flatMap(a => a.filings.map(f => f.frDoc)).filter(Boolean);

// Evaluated once at load, not during render: how far behind the committed
// dataset is. If this starts climbing, the update workflow has stopped running.
const STALE_DAYS = Math.floor((Date.now() - new Date(DATA.generatedAt).getTime()) / 86400000);

const STATUS_CFG = {
  "Effective":      { bg:"#052e16", text:"#4ade80", border:"#166534", dot:"#22c55e" },
  "Comment Period": { bg:"#1c1917", text:"#fb923c", border:"#9a3412", dot:"#f97316" },
  "Not Filed":      { bg:"#1a0a0a", text:"#f87171", border:"#7f1d1d", dot:"#ef4444" },
};

const KIND_COLOR = {
  "Matching Program": "#a78bfa",
  "SORN Modification": "#60a5fa",
  "New SORN": "#34d399",
  "Rescindment": "#f87171",
};

const fmtDate = iso => {
  if (!iso) return null;
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString("en-US", {
    month: "short", day: "numeric", year: "numeric", timeZone: "UTC",
  });
};

function Dot({ status }) {
  const c = STATUS_CFG[status];
  return <span style={{ display:"inline-block", width:7, height:7, borderRadius:"50%", background:c.dot, marginRight:5, flexShrink:0, boxShadow: status==="Effective"?`0 0 5px ${c.dot}66`:"none" }} />;
}

function Badge({ status }) {
  const c = STATUS_CFG[status];
  return (
    <span style={{ background:c.bg, color:c.text, border:`1px solid ${c.border}`, borderRadius:3, padding:"2px 7px", fontSize:10, fontFamily:"monospace", whiteSpace:"nowrap", display:"inline-flex", alignItems:"center" }}>
      <Dot status={status}/>{status}
    </span>
  );
}

function Chip({ s }) {
  return <span style={{ background:"#0d1117", color:"#6b7280", border:"1px solid #1f2937", borderRadius:3, padding:"2px 5px", fontSize:10, fontFamily:"monospace", display:"inline-block", margin:"2px 2px 2px 0" }}>{s}</span>;
}

function Filing({ f, asOf }) {
  const open = f.commentsCloseOn && f.commentsCloseOn >= asOf;
  const kindColor = KIND_COLOR[f.kind] ?? "#6b7280";
  return (
    <div style={{ display:"flex", alignItems:"baseline", gap:9, padding:"6px 0", borderBottom:"1px solid #0d1a2d", flexWrap:"wrap" }}>
      <span style={{ fontSize:10, color:"#6b7280", fontFamily:"monospace", whiteSpace:"nowrap", minWidth:86 }}>{fmtDate(f.pubDate) ?? "—"}</span>
      <span style={{ fontSize:9, color:kindColor, border:`1px solid ${kindColor}44`, borderRadius:3, padding:"1px 5px", fontFamily:"monospace", whiteSpace:"nowrap" }}>{f.kind}</span>
      <span style={{ fontSize:10, color:"#4b5563", fontFamily:"monospace", whiteSpace:"nowrap" }}>{f.frCitation ?? f.frDoc}</span>
      {open && (
        <span style={{ fontSize:9, color:"#fb923c", border:"1px solid #9a3412", borderRadius:3, padding:"1px 5px", fontFamily:"monospace", whiteSpace:"nowrap" }}>
          comments close {fmtDate(f.commentsCloseOn)}
        </span>
      )}
      {!open && f.commentsCloseOn && (
        <span style={{ fontSize:9, color:"#374151", fontFamily:"monospace", whiteSpace:"nowrap" }}>closed {fmtDate(f.commentsCloseOn)}</span>
      )}
      <a href={f.frUrl} target="_blank" rel="noreferrer" style={{ fontSize:10, color:"#3b82f6", textDecoration:"none", fontFamily:"monospace", marginLeft:"auto", whiteSpace:"nowrap" }}>
        {f.frDoc} ↗
      </a>
    </div>
  );
}

function Row({ a, asOf, isOpen, onToggle }) {
  const c = STATUS_CFG[a.status];
  const filed = a.filingCount > 0;
  const latest = a.latest;
  const openWindow = a.filings.find(f => f.commentsCloseOn && f.commentsCloseOn >= asOf);

  return (
    <div style={{ background:"#08111e", border:`1px solid ${isOpen?c.border:"#111827"}`, borderRadius:5, marginBottom:5, overflow:"hidden", transition:"border-color 0.15s" }}>
      <div onClick={onToggle} style={{ display:"grid", gridTemplateColumns:"22px 2fr 105px 125px 80px 130px 20px", gap:10, padding:"11px 14px", cursor:"pointer", alignItems:"center" }}>
        <span style={{ fontSize:8, color:"#1f2937", border:"1px solid #1f2937", borderRadius:2, padding:"1px 2px", fontFamily:"monospace", textAlign:"center", lineHeight:1.4 }}>
          {a.type==="CFO Act"?"CFO":"IND"}
        </span>
        <div>
          <span style={{ fontSize:13, fontWeight:600, color:"#f3f4f6" }}>{a.agency}</span>
          <span style={{ fontSize:10, color:"#374151", fontFamily:"monospace", marginLeft:6 }}>({a.abbr})</span>
        </div>
        <span style={{ fontSize:11, color:filed?"#6b7280":"#1f2937", fontFamily:"monospace" }}>{latest?.pubDate ?? "—"}</span>
        <span style={{ fontSize:11, color:openWindow?"#fb923c":filed?"#6b7280":"#1f2937", fontFamily:"monospace" }}>
          {openWindow ? openWindow.commentsCloseOn : latest?.commentsCloseOn ?? latest?.effectiveDate ?? "—"}
        </span>
        <span style={{ fontSize:11, color:filed?"#6b7280":"#1f2937", fontFamily:"monospace" }}>
          {filed ? `${a.filingCount} notice${a.filingCount===1?"":"s"}` : "—"}
        </span>
        <Badge status={a.status}/>
        <span style={{ color:"#374151", fontSize:10, textAlign:"right" }}>{isOpen?"▲":"▼"}</span>
      </div>

      {isOpen && (
        <div style={{ borderTop:"1px solid #0d1117", padding:"12px 14px", background:"#050c18" }}>
          {(a.notes || a.sorns.length > 0) && (
            <div style={{ display:"grid", gridTemplateColumns: a.sorns.length ? "1fr 1fr" : "1fr", gap:16, marginBottom:12 }}>
              {a.sorns.length > 0 && (
                <div>
                  <div style={{ fontSize:9, color:"#374151", textTransform:"uppercase", letterSpacing:"0.1em", marginBottom:5 }}>SORNs Modified (curated)</div>
                  <div>{a.sorns.map(s=><Chip key={s} s={s}/>)}</div>
                </div>
              )}
              {a.notes && (
                <div>
                  <div style={{ fontSize:9, color:"#374151", textTransform:"uppercase", letterSpacing:"0.1em", marginBottom:5 }}>
                    {filed ? "Notes" : "Compliance Context"}
                  </div>
                  <p style={{ margin:0, fontSize:12, color:"#9ca3af", lineHeight:1.6 }}>{a.notes}</p>
                </div>
              )}
            </div>
          )}

          {filed ? (
            <>
              <div style={{ fontSize:9, color:"#374151", textTransform:"uppercase", letterSpacing:"0.1em", marginBottom:3 }}>
                Federal Register Notices — {a.filingCount}
              </div>
              {a.filings.map(f => <Filing key={f.frDoc} f={f} asOf={asOf}/>)}
            </>
          ) : (
            <div style={{ display:"flex" }}>
              <a href={`https://www.federalregister.gov/agencies/${a.slug}`} target="_blank" rel="noreferrer"
                style={{ fontSize:10, color:"#3b82f6", textDecoration:"none", fontFamily:"monospace", marginLeft:"auto", border:"1px solid #1e3a5f", padding:"3px 9px", borderRadius:4 }}>
                Agency FR Page ↗
              </a>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default function App() {
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");
  const [typeFilter, setTypeFilter] = useState("All");
  const [view, setView] = useState("gap");
  const [expanded, setExpanded] = useState(null);
  const [liveOpen, setLiveOpen] = useState(false);

  const asOf = DATA.asOf;
  const { results: liveResults, loading: liveLoading, error: liveError, lastChecked, refetch } =
    useFRLiveSearch(KNOWN_FR_DOCS);

  const stats = useMemo(() => ({
    total: AGENCIES.length,
    effective: AGENCIES.filter(a=>a.status==="Effective").length,
    comment: AGENCIES.filter(a=>a.status==="Comment Period").length,
    notFiled: AGENCIES.filter(a=>a.status==="Not Filed").length,
    cfoFiled: AGENCIES.filter(a=>a.type==="CFO Act"&&a.status!=="Not Filed").length,
    cfoTotal: AGENCIES.filter(a=>a.type==="CFO Act").length,
    filings: DATA.totals.filings,
  }), []);

  const filtered = useMemo(() => AGENCIES.filter(a => {
    const q = search.toLowerCase();
    return (!q
        || a.agency.toLowerCase().includes(q)
        || a.abbr.toLowerCase().includes(q)
        || a.sorns.some(s=>s.toLowerCase().includes(q))
        || a.filings.some(f=>(f.frDoc??"").toLowerCase().includes(q) || (f.frCitation??"").toLowerCase().includes(q)))
      && (statusFilter==="All" || a.status===statusFilter)
      && (typeFilter==="All" || a.type===typeFilter);
  }), [search, statusFilter, typeFilter]);

  const pct = Math.round(((stats.effective+stats.comment)/stats.total)*100);
  const filed = filtered.filter(a=>a.status!=="Not Filed");
  const notFiled = filtered.filter(a=>a.status==="Not Filed");
  const openComment = AGENCIES.filter(a=>a.status==="Comment Period");

  const toggle = key => setExpanded(expanded===key?null:key);

  return (
    <div style={{ minHeight:"100vh", background:"#030712", color:"#e5e7eb", fontFamily:"'Helvetica Neue',Arial,sans-serif" }}>

      {/* HEADER */}
      <div style={{ borderBottom:"1px solid #0d1a2d", background:"#020b17", padding:"24px 32px 18px" }}>
        <div style={{ fontSize:9, color:"#1e3a5f", letterSpacing:"0.2em", textTransform:"uppercase", fontFamily:"monospace", marginBottom:5 }}>EO 14249 · OMB M-25-32 · Privacy Act Compliance</div>
        <h1 style={{ margin:"0 0 4px", fontSize:19, fontWeight:700, color:"#f9fafb", letterSpacing:"-0.02em" }}>Do Not Pay SORN Routine Use — Compliance Tracker</h1>
        <p style={{ margin:0, fontSize:12, color:"#4b5563", maxWidth:700 }}>
          Agency Federal Register filings adding the Treasury Do Not Pay routine use to Privacy Act SORNs, plus PIIA computer matching programs against the DNP Working System.{" "}
          <span style={{ color: STALE_DAYS > 3 ? "#fb923c" : "#4b5563", fontFamily:"monospace" }}>
            Data generated {fmtDate(DATA.asOf)}{STALE_DAYS > 3 ? ` (${STALE_DAYS} days ago)` : ""}.
          </span>
        </p>

        {openComment.length > 0 && (
          <div style={{ marginTop:12, background:"#1c1917", border:"1px solid #9a3412", borderLeft:"3px solid #f97316", borderRadius:4, padding:"8px 12px", maxWidth:820 }}>
            <div style={{ fontSize:9, color:"#9a3412", letterSpacing:"0.12em", textTransform:"uppercase", marginBottom:4 }}>Open for public comment</div>
            <div style={{ fontSize:11, color:"#fdba74", lineHeight:1.7 }}>
              {openComment.map(a => {
                const f = a.filings.find(x=>x.commentsCloseOn && x.commentsCloseOn >= asOf);
                return (
                  <span key={a.slug} style={{ marginRight:14, whiteSpace:"nowrap" }}>
                    <strong>{a.abbr}</strong> <a href={f.frUrl} target="_blank" rel="noreferrer" style={{ color:"#fb923c", textDecoration:"none" }}>{f.frDoc} ↗</a>{" "}
                    <span style={{ color:"#9a3412" }}>closes {fmtDate(f.commentsCloseOn)}</span>
                  </span>
                );
              })}
            </div>
          </div>
        )}

        <div style={{ display:"flex", gap:8, marginTop:16, flexWrap:"wrap" }}>
          {[
            { l:"Agencies Tracked", v:stats.total, c:"#60a5fa" },
            { l:"Effective", v:stats.effective, c:"#22c55e" },
            { l:"Comment Period", v:stats.comment, c:"#f97316" },
            { l:"Not Filed", v:stats.notFiled, c:"#ef4444" },
            { l:"CFO Act Filed", v:`${stats.cfoFiled}/${stats.cfoTotal}`, c:"#a78bfa" },
            { l:"FR Notices", v:stats.filings, c:"#34d399" },
          ].map(s=>(
            <div key={s.l} style={{ background:"#080f1a", border:"1px solid #111f30", borderRadius:5, padding:"7px 12px" }}>
              <div style={{ fontSize:17, fontWeight:700, color:s.c, fontFamily:"monospace" }}>{s.v}</div>
              <div style={{ fontSize:9, color:"#374151", marginTop:1 }}>{s.l}</div>
            </div>
          ))}
        </div>

        <div style={{ marginTop:14, maxWidth:480 }}>
          <div style={{ display:"flex", justifyContent:"space-between", marginBottom:3 }}>
            <span style={{ fontSize:9, color:"#374151" }}>Compliance progress (filed / total tracked)</span>
            <span style={{ fontSize:9, color:"#4b5563", fontFamily:"monospace" }}>{pct}%</span>
          </div>
          <div style={{ background:"#0a1525", borderRadius:3, height:5, overflow:"hidden" }}>
            <div style={{ height:"100%", borderRadius:3, width:`${pct}%`, background:"linear-gradient(90deg,#1d4ed8,#22c55e)", transition:"width 0.5s" }}/>
          </div>
          <div style={{ display:"flex", gap:12, marginTop:5 }}>
            {[["#22c55e",`Effective (${stats.effective})`],["#f97316",`Comment Period (${stats.comment})`],["#ef4444",`Not Filed (${stats.notFiled})`]].map(([c,l])=>(
              <span key={l} style={{ fontSize:9, color:c }}>■ {l}</span>
            ))}
          </div>
        </div>

        {/* LIVE FR FEED */}
        <div style={{ marginTop: 16, maxWidth: 820 }}>
          <button
            onClick={() => setLiveOpen(o => !o)}
            style={{ background: "none", border: "1px solid #1e3a5f", borderRadius: 4, color: "#3b82f6", fontSize: 10, fontFamily: "monospace", padding: "4px 10px", cursor: "pointer", display: "flex", alignItems: "center", gap: 6 }}
          >
            <span style={{ display: "inline-block", width: 7, height: 7, borderRadius: "50%", background: liveLoading ? "#f97316" : liveError ? "#ef4444" : "#22c55e", boxShadow: !liveLoading && !liveError ? "0 0 5px #22c55e66" : "none" }} />
            Live FR Feed
            {!liveLoading && !liveError && liveResults.some(r => r.isNew) && (
              <span style={{ background: "#7c3aed", color: "#e9d5ff", borderRadius: 3, padding: "1px 5px", fontSize: 9 }}>
                {liveResults.filter(r => r.isNew).length} NOT IN DATASET
              </span>
            )}
            <span style={{ color: "#374151" }}>{liveOpen ? "▲" : "▼"}</span>
          </button>

          {liveOpen && (
            <div style={{ marginTop: 6, background: "#060d1a", border: "1px solid #162540", borderRadius: 4, padding: "10px 14px" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8, gap: 10 }}>
                <span style={{ fontSize: 9, color: "#374151", textTransform: "uppercase", letterSpacing: "0.12em" }}>
                  {liveLoading ? "Querying Federal Register…" : liveError ? `Error: ${liveError}` : `${liveResults.length} most recent notices · checked ${lastChecked?.toLocaleTimeString()}`}
                </span>
                <button onClick={refetch} disabled={liveLoading} style={{ background: "none", border: "1px solid #1e3a5f", borderRadius: 3, color: "#3b82f6", fontSize: 9, fontFamily: "monospace", padding: "2px 7px", cursor: "pointer" }}>
                  ↺ Refresh
                </button>
              </div>
              {!liveLoading && !liveError && liveResults.map(doc => (
                <div key={doc.document_number} style={{ display: "flex", alignItems: "baseline", gap: 8, padding: "5px 0", borderBottom: "1px solid #0d1a2d" }}>
                  {doc.isNew && (
                    <span style={{ background: "#4c1d95", color: "#c4b5fd", border: "1px solid #6d28d9", borderRadius: 3, padding: "1px 5px", fontSize: 9, fontFamily: "monospace", whiteSpace: "nowrap", flexShrink: 0 }}>NEW</span>
                  )}
                  <span style={{ fontSize: 10, color: "#6b7280", fontFamily: "monospace", whiteSpace: "nowrap", flexShrink: 0 }}>{doc.publication_date}</span>
                  <a href={doc.html_url} target="_blank" rel="noreferrer" style={{ fontSize: 11, color: doc.isNew ? "#c4b5fd" : "#4b5563", textDecoration: "none", lineHeight: 1.4, flex: 1 }}>
                    {doc.agencyNames} — {doc.title}
                  </a>
                  <span style={{ fontSize: 9, color: "#374151", fontFamily: "monospace", whiteSpace: "nowrap", flexShrink: 0 }}>{doc.document_number}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* ROUTINE USE */}
      <div style={{ padding:"12px 32px 0" }}>
        <div style={{ background:"#060d1a", border:"1px solid #162540", borderLeft:"3px solid #1d4ed8", borderRadius:4, padding:"10px 14px", maxWidth:820 }}>
          <div style={{ fontSize:8, color:"#1e3a5f", letterSpacing:"0.12em", textTransform:"uppercase", marginBottom:5 }}>Standardized Routine Use — OMB M-25-32</div>
          <p style={{ margin:0, fontSize:11, color:"#4b5563", lineHeight:1.7, fontStyle:"italic" }}>"{ROUTINE_USE}"</p>
        </div>
      </div>

      {/* CONTROLS */}
      <div style={{ padding:"14px 32px 8px", display:"flex", gap:8, alignItems:"center", flexWrap:"wrap" }}>
        <div style={{ display:"flex", background:"#080f1a", border:"1px solid #111f30", borderRadius:5, overflow:"hidden" }}>
          {[["list","All Agencies"],["gap","Compliance Gap"]].map(([v,l])=>(
            <button key={v} onClick={()=>setView(v)} style={{ background:view===v?"#162540":"transparent", border:"none", color:view===v?"#93c5fd":"#374151", padding:"6px 13px", fontSize:11, cursor:"pointer", fontFamily:"monospace" }}>{l}</button>
          ))}
        </div>
        <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search agency, SORN, FR doc…"
          style={{ background:"#080f1a", border:"1px solid #111f30", borderRadius:4, color:"#e5e7eb", padding:"5px 11px", fontSize:11, width:210, outline:"none" }}/>
        {["All","Effective","Comment Period","Not Filed"].map(f=>(
          <button key={f} onClick={()=>setStatusFilter(f)} style={{ background:statusFilter===f?"#162540":"#080f1a", border:`1px solid ${statusFilter===f?"#3b82f6":"#111f30"}`, borderRadius:4, color:statusFilter===f?"#93c5fd":"#374151", padding:"5px 11px", fontSize:10, cursor:"pointer", fontFamily:"monospace" }}>{f}</button>
        ))}
        {["All","CFO Act","Independent"].map(t=>(
          <button key={t} onClick={()=>setTypeFilter(t)} style={{ background:typeFilter===t?"#1a1040":"#080f1a", border:`1px solid ${typeFilter===t?"#7c3aed":"#111f30"}`, borderRadius:4, color:typeFilter===t?"#a78bfa":"#374151", padding:"5px 11px", fontSize:10, cursor:"pointer", fontFamily:"monospace" }}>{t}</button>
        ))}
        <a href={FR_SEARCH_URL} target="_blank" rel="noreferrer"
          style={{ marginLeft:"auto", fontSize:10, color:"#3b82f6", textDecoration:"none", fontFamily:"monospace", border:"1px solid #1e3a5f", padding:"5px 11px", borderRadius:4 }}>
          🔍 Live FR Search ↗
        </a>
      </div>

      {/* TABLE HEADER */}
      <div style={{ padding:"0 32px" }}>
        <div style={{ display:"grid", gridTemplateColumns:"22px 2fr 105px 125px 80px 130px 20px", gap:10, padding:"4px 14px 7px", fontSize:8, color:"#1f2937", textTransform:"uppercase", letterSpacing:"0.1em" }}>
          <div></div><div>Agency</div><div>Latest Filing</div><div>Comments Close</div><div>Notices</div><div>Status</div><div></div>
        </div>
      </div>

      {/* ROWS */}
      <div style={{ padding:"0 32px 36px" }}>
        {view==="list" ? (
          filtered.map(a=><Row key={a.slug} a={a} asOf={asOf} isOpen={expanded===a.slug} onToggle={()=>toggle(a.slug)}/>)
        ) : (
          <>
            {filed.length>0 && (
              <>
                <div style={{ fontSize:9, color:"#22c55e", textTransform:"uppercase", letterSpacing:"0.15em", fontFamily:"monospace", padding:"6px 0 5px", borderBottom:"1px solid #0a2010", marginBottom:7 }}>
                  ✓ Filed &amp; Confirmed — {filed.length} {filed.length===1?"Agency":"Agencies"}
                </div>
                {filed.map(a=><Row key={a.slug} a={a} asOf={asOf} isOpen={expanded===a.slug} onToggle={()=>toggle(a.slug)}/>)}
              </>
            )}
            {notFiled.length>0 && (
              <>
                <div style={{ fontSize:9, color:"#ef4444", textTransform:"uppercase", letterSpacing:"0.15em", fontFamily:"monospace", padding:"16px 0 5px", borderBottom:"1px solid #1a0505", marginBottom:7 }}>
                  ✗ Not Yet Filed — {notFiled.length} {notFiled.length===1?"Agency":"Agencies"}
                </div>
                {notFiled.map(a=><Row key={a.slug} a={a} asOf={asOf} isOpen={expanded===a.slug} onToggle={()=>toggle(a.slug)}/>)}
              </>
            )}
          </>
        )}
        {filtered.length===0 && (
          <div style={{ textAlign:"center", padding:40, color:"#1f2937", fontSize:12 }}>No agencies match your filters.</div>
        )}

        <div style={{ marginTop:18, padding:"11px 14px", background:"#060b14", border:"1px solid #0d1a2d", borderRadius:5, fontSize:10, color:"#374151", lineHeight:1.8 }}>
          <span style={{ color:"#4b5563" }}>⚠ Method:</span> Statuses are <em>derived from Federal Register dates</em>, not hand-set.
          <strong> Comment Period</strong> = at least one notice whose comment window is still open as of {fmtDate(asOf)}.
          <strong> Effective</strong> = notices located and no comment window open.
          <strong> Not Filed</strong> = no matching notice located — large agencies may have filed under component notices phrased differently.
          Agencies listed in <code>src/data/overrides.json</code> always appear even with zero filings; any other agency appears automatically once it files.
          EO 14249 applies to <em>all</em> executive agencies — non-CFO Act agencies are equally required to comply.
        </div>
      </div>
    </div>
  );
}
